name: synapsis_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  modal_progress_hud_nsn: ^0.4.0
  logging: ^1.2.0
  fluttertoast: ^8.2.2
  local_auth: ^2.1.6
  nfc_manager: ^3.3.0
  sensors_plus: ^3.0.2
  device_info_plus: ^9.0.2
  battery_info: ^1.1.1
  intl: ^0.17.0
  geolocator: ^8.0.0
  path: ^1.8.3
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  syncfusion_flutter_charts: ^20.2.41

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - data/user.db
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700